#
# buildspec.yml
#

version: 0.2

env:
  variables:
    deploy_bucket: aptrust-submit-lambda-deployable

phases:
  install:
    runtime-versions:
      golang: 1.x
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo ${CODEBUILD_START_TIME} | cut -c1-10)" +"%Y%m%d%H%M%S")
      - COMMIT_TAG=gitcommit-${CODEBUILD_RESOLVED_SOURCE_VERSION}

  build:
    commands:
      #
      # build the assets
      #
      # apt-submit-bag-status function
      - cd ${CODEBUILD_SRC_DIR}/apt-submit-bag-status
      - make linux
      #
      # apt-submit-event-audit function
      - cd ${CODEBUILD_SRC_DIR}/apt-submit-event-audit
      - make linux
      #
      # apt-submit-schedule function
      - cd ${CODEBUILD_SRC_DIR}/apt-submit-schedule
      - make linux
      #
      # apt-submit-submission-initiate function
      - cd ${CODEBUILD_SRC_DIR}/apt-submit-submission-initiate
      - make linux
      #
      # apt-submit-submission-register function
      - cd ${CODEBUILD_SRC_DIR}/apt-submit-submission-register
      - make linux
      #
      # apt-submit-submission-status function
      - cd ${CODEBUILD_SRC_DIR}/apt-submit-submission-status
      - make linux
      #
      # copy to the results bucket
      #
      # apt-submit-bag-status function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apt-submit-bag-status/bin/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/apt-submit-bag-status/deployment.zip --quiet
      #
      # apt-submit-event-audit function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apt-submit-event-audit/bin/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/apt-submit-event-audit/deployment.zip --quiet
      #
      # apt-submit-schedule function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apt-submit-schedule/bin/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/apt-submit-schedule/deployment.zip --quiet
      #
      # apt-submit-submission-initiate function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apt-submit-submission-initiate/bin/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/apt-submit-submission-initiate/deployment.zip --quiet
      #
      # apt-submit-submission-register function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apt-submit-submission-register/bin/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/apt-submit-submission-register/deployment.zip --quiet
      #
      # apt-submit-submission-status function
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apt-submit-submission-status/bin/deployment.zip s3://${deploy_bucket}/${BUILD_VERSION}/apt-submit-submission-status/deployment.zip --quiet
      #
      # migrations
      - aws s3 cp ${CODEBUILD_SRC_DIR}/db/migrations s3://${deploy_bucket}/${BUILD_VERSION}/migrations --recursive --include *.sql --quiet
      #
      # scripts
      - aws s3 cp ${CODEBUILD_SRC_DIR}/scripts s3://${deploy_bucket}/${BUILD_VERSION}/scripts --recursive --include *.ksh --quiet
      #
      # create the git commit tag file
      #
      - touch ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git
      - aws s3 cp ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git s3://${deploy_bucket}/${BUILD_VERSION}/${COMMIT_TAG}.git --quiet
      #
      # make the latest folder
      #
      - aws s3 sync s3://${deploy_bucket}/${BUILD_VERSION} s3://${deploy_bucket}/latest --delete --quiet
      #
      # update the latest tag
      #
      - aws --region=$AWS_REGION ssm put-parameter --name /lambdas/${deploy_bucket}/latest --value ${BUILD_VERSION} --type String --overwrite

#  post_build:
#    commands:

#
# end of file
#
