package main

import (
	"github.com/uvalib/aptrust-submit-bus-definitions/uvaaptsbus"
	"github.com/uvalib/aptrust-submit-db-dao/uvaaptsdao"
)

// ready to approve the submission
//func handleSubmissionApprove(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {
//
//	// get the client details
//	cli, err := dao.GetClientByIdentifier(busEvent.ClientId)
//	if err != nil {
//		fmt.Printf("ERROR: client details not found [%s] (%s)\n", busEvent.ClientId, err.Error())
//		return err
//	}
//
//	// if we do not require manual approval, just generate the "approved" event automatically
//	// otherwise, it will be generated by user action
//	if len(cli.ApprovalEmail) == 0 {
//		err = publishWorkflowEvent(bus, uvaaptsbus.EventSubmissionApproved, busEvent.ClientId, workflowEvent.SubmissionId, "", "<system>")
//	}
//	return err
//}

// submission needs to be approved
func handleSubmissionApprove(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	// update the state of the submission
	err := dao.UpdateSubmissionState(workflowEvent.SubmissionId, SubmissionStatusPendingApproval)
	return err
}

// submission was approved
func handleSubmissionApproved(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	// update the state of the submission
	err := dao.UpdateSubmissionState(workflowEvent.SubmissionId, SubmissionStatusBuilding)
	return err
}

// bag was successfully submitted to APT
func handleBagSubmitted(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	// update the state of the bag
	err := dao.UpdateBagState(workflowEvent.BagId, workflowEvent.SubmissionId, BagStatusPendingIngest)
	if err != nil {
		return err
	}

	// also apply the etag cos it is contained in this event
	err = dao.UpdateBagETag(workflowEvent.BagId, workflowEvent.SubmissionId, workflowEvent.Extra)

	return err
}

//
// end of file
//
