package main

import (
	"fmt"

	"github.com/uvalib/aptrust-submit-bus-definitions/uvaaptsbus"
	"github.com/uvalib/aptrust-submit-db-dao/uvaaptsdao"
)

// ready to approve the submission
func handleSubmissionApprove(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	// get the client details
	cli, err := dao.GetClientByIdentifier(busEvent.ClientId)
	if err != nil {
		fmt.Printf("ERROR: client details not found [%s] (%s)\n", busEvent.ClientId, err.Error())
		return err
	}

	// if we do not require manual approval, just generate the "approved" event automatically
	// otherwise, it will be generated by user action
	if len(cli.ApprovalEmail) == 0 {
		err = publishWorkflowEvent(bus, uvaaptsbus.EventSubmissionApproved, busEvent.ClientId, workflowEvent.SubmissionId, "", "<system>")
	}
	return err
}

// submission was approved
func handleSubmissionApproval(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	ss, err := dao.GetSubmissionStateByIdentifier(workflowEvent.SubmissionId)
	if err != nil {
		fmt.Printf("ERROR: getting submission state (%s)\n", err.Error())
		return err
	}

	// validate that the submission state is as expected
	if ss.State != uvaaptsdao.SubmissionStatusPendingApproval {
		err = fmt.Errorf("submission [%s] in incorrect state for approvals (%s)", workflowEvent.SubmissionId, ss.State)
		fmt.Printf("ERROR: %s\n", err.Error())
		return err
	}

	// get all the bags for this submission
	bags, err := dao.GetBagsBySubmission(workflowEvent.SubmissionId)
	if err != nil {
		fmt.Printf("ERROR: getting submission bags (%s)\n", err.Error())
		return err
	}

	// and generate a bag initiate event for each one
	var res error
	for _, bag := range bags {
		err = publishWorkflowEvent(bus, uvaaptsbus.EventBagInitiate, busEvent.ClientId, workflowEvent.SubmissionId, bag.Name, "")
		if err != nil {
			res = err
		}
	}

	return res
}

// submission was abandoned
func handleSubmissionAbandoned(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {
	// not sure what to do here yet...
	return nil
}

//
// end of file
//
