package main

import (
	"fmt"

	"github.com/uvalib/aptrust-submit-bus-definitions/uvaaptsbus"
	"github.com/uvalib/aptrust-submit-db-dao/uvaaptsdao"
)

// ready to approve the submission
func handleSubmissionApprove(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	// get the client details
	cli, err := dao.GetClientByIdentifier(busEvent.ClientId)
	if err != nil {
		fmt.Printf("ERROR: client details not found [%s] (%s)\n", busEvent.ClientId, err.Error())
		return err
	}

	// update the state of the submission
	err = dao.UpdateSubmissionState(workflowEvent.SubmissionId, uvaaptsdao.SubmissionStatusPendingApproval)
	if err != nil {
		fmt.Printf("ERROR: updating submission state [%s] (%s)\n", workflowEvent.SubmissionId, err.Error())
		return err
	}

	// if we do not require manual approval, just generate the "approved" event automatically
	// otherwise, it will be generated by user action
	if len(cli.ApprovalEmail) == 0 {
		err = publishWorkflowEvent(bus, uvaaptsbus.EventSubmissionApproved, busEvent.ClientId, workflowEvent.SubmissionId, "", "<system>")
	}

	return err
}

// submission was approved
func handleSubmissionApproval(bus uvaaptsbus.UvaBus, busEvent *uvaaptsbus.UvaBusEvent, workflowEvent *uvaaptsbus.UvaWorkflowEvent, dao *uvaaptsdao.Dao) error {

	ss, err := dao.GetSubmissionStateByIdentifier(workflowEvent.SubmissionId)
	if err != nil {
		fmt.Printf("ERROR: getting submission state (%s)\n", err.Error())
		return err
	}

	// validate that the submission state is as expected
	if ss.State != uvaaptsdao.SubmissionStatusPendingApproval {
		err = fmt.Errorf("submission [%s] in incorrect state for approvals (%s)", workflowEvent.SubmissionId, ss.State)
		fmt.Printf("ERROR: %s\n", err.Error())
		return err
	}

	// get all the bags for this submission
	bags, err := dao.GetBagsBySubmission(workflowEvent.SubmissionId)
	if err != nil {
		fmt.Printf("ERROR: getting submission bags (%s)\n", err.Error())
		return err
	}

	// and generate a bag initiate event for each one
	for _, bag := range bags {
		err = publishWorkflowEvent(bus, uvaaptsbus.EventBagInitiate, busEvent.ClientId, workflowEvent.SubmissionId, bag.Name, "")
		if err != nil {
			fmt.Printf("ERROR: publishing bag initiate event for <%s:%s>, continuing (%s)\n", workflowEvent.SubmissionId, bag.Name, err.Error())
		}
	}

	// audit the approval cos the approver is contained in this event
	err = dao.AddApproval(workflowEvent.SubmissionId, workflowEvent.Extra)
	if err != nil {
		fmt.Printf("ERROR: adding approval record for [%s], continuing (%s)\n", workflowEvent.SubmissionId, err.Error())
	}

	// update the state of the submission
	return dao.UpdateSubmissionState(workflowEvent.SubmissionId, uvaaptsdao.SubmissionStatusBuilding)
}

//
// end of file
//
